# Group ngi-sw MUST have rw or else all hell breaks loose! 
umask 0002

# Bootstrap a log directory 
mkdir -p /lupus/ngi/irma3/log

# These days irma3 mounts home dirs from pica instead so it is 
# hopefully not needed anymore.
#
# We need a writeable place when running Ansible for tmp files
#export HOME=/tmp/ngi-sw-`whoami`
#export HOME=/tmp/ngi-sw-home/
#mkdir -p $HOME 

# At the moment these aliases will not work because the required 
# newgrp command in the end of the file. 
#
# We need the Ansible env for running ansible commands 
#alias ansibleenv='source /lupus/ngi/irma3/ansible-env/bin/activate'

# We're using Anaconda when setting up the NGI pipeline environment. 
# Perhaps not necessary.
# TODO: Remove this when we know that Anaconda install/env works
# properly from within Ansible playbooks.
#export PATH="/lupus/ngi/sw/anaconda/bin:$PATH"

# Force the user to have ngi-sw as gid (inherits the parent environment)
# This needs to be the last thing to run 
newgrp ngi-sw 
