---
- name: create tarzan root dir
  file:
    name: "{{ tarzan_root_dir }}"
    state: directory

- name: create tarzan conf dir
  file:
    name: "{{ tarzan_conf_dir }}"
    state: directory

- name: deploy server config file for kong
  template:
    src: "kong.conf.j2"
    dest: "{{ tarzan_server_conf_file }}"

- name: deploy entity config file for kong
  template:
    src: "kong.yml.j2"
    dest: "{{ tarzan_entity_conf_file }}"

- name: deploy kong start script
  template:
    src: "start_kong.sh.j2"
    dest: "{{ tarzan_start_script }}"
    mode: 0775

- name: create tarzan singularity image dir
  file:
    name: "{{ tarzan_singularity_image_file_dest | dirname }}"
    state: directory

- name: deploy singularity image for kong
  copy:
    src: "{{ tarzan_singularity_image_file_src }}"
    dest: "{{ tarzan_singularity_image_file_dest }}"
    checksum: "{{ tarzan_singularity_image_sha1 }}"

# Couldn't get this to work properly with supervisord because
# it demands that the program under control doesn't daemonize.
- name: modify crontab to start kong
  lineinfile: dest="{{ ngi_pipeline_conf }}/crontab_{{ site }}"
              line='# restart kong if it has died for some reason'
              backup=no

- name: modify crontab to start kong
  lineinfile: dest="{{ ngi_pipeline_conf }}/crontab_{{ site }}"
              line='@reboot source $HOME/.bash_profile && {{ tarzan_start_script }}'
              backup=no

- name: modify uppsala's crontab to start kong
  lineinfile: dest="{{ ngi_pipeline_conf }}/crontab_upps"
              line='38 * * * *      source $HOME/.bash_profile && {{ tarzan_start_script }} &> /dev/null'
              backup=no

- name: Store tarzan tools version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "Kong: {{ tarzan_kong_version }}"
