---
- name: create tarzan root dir
  file:
    name: "{{ tarzan_root_dir }}"
    state: directory

- name: create tarzan conf dir
  file:
    name: "{{ tarzan_conf_dir }}"
    state: directory

- name: deploy server config file for kong
  template:
    src: "kong.conf.j2"
    dest: "{{ tarzan_server_conf_file }}"

- name: deploy entity config file for kong
  template:
    src: "kong.yml.j2"
    dest: "{{ tarzan_entity_conf_file }}"

- name: deploy cert config file for kong
  template:
    src: "tarzan_cert_config.txt.j2"
    dest: "{{ tarzan_cert_conf_file }}"

- name: deploy kong start script
  template:
    src: "start_kong.sh.j2"
    dest: "{{ tarzan_start_script }}"
    mode: 0775

- name: create tarzan singularity image dir
  file:
    name: "{{ tarzan_singularity_image_file_dest | dirname }}"
    state: directory

- name: deploy singularity image for kong
  copy:
    src: "{{ tarzan_singularity_image_file_src }}"
    dest: "{{ tarzan_singularity_image_file_dest }}"
    checksum: "{{ tarzan_singularity_image_sha1 }}"

- name: modify crontab to start kong
  lineinfile:
    dest: "{{ ngi_pipeline_conf }}/crontab_{{ site }}"
    line: '@reboot source $HOME/.bash_profile && {{ tarzan_start_script }} &> /dev/null'
    backup: no

- name: add static folders to be created
  set_fact:
    static_folders: "{{ static_folders + [tarzan_proj_dir, tarzan_log_dir, tarzan_cert_dir] }}"

- name: Store tarzan tools version in deployment
  lineinfile:
    dest: "{{ deployed_tool_versions }}"
    line: "Kong: {{ tarzan_kong_version }}"
