---

- name: Deploy irma software
  hosts: 127.0.0.1
  connection: local

  # These three variables needs to be overriden when calling ansible-playbook.
  #
  # Call with e.g. "ansible-playbook install.yml -e deployment_environment=staging -e deployment_version=foo".
  # If devel then the version will always be set to USERNAME_BRANCHNAME.
  # If staging or production then the playbook will halt if the folder version already exists.
  # I.e. the user will then manually have to remove the directory, OR add "-e deployment_override=true"
  # to deploy into an already existing folder.
  #
  # /lupus/ngi/production/<latest|current> will link to /lupus/ngi/production/<github release>
  # /lupus/ngi/staging/ will contain a folder wild-wild-west which will be world writeable ON THE RECIEVING end. I.e. the
  # sync script will change the permissions? This is to make sure that not everyone that is able to login to irma3 can
  # upload data into the cluster.
  vars:
    deployment_environment: devel # should be: 1) production, 2) staging, 3) devel
    deployment_version: default # should be: 1) autogenerated for devel, 2) commit-hash for staging, 3) repo release tag for production
    deployment_override: false # Set to true if you want to deploy into existing production/staging environment
    deployment_local_path: "{{ lookup('env', 'DEPLOYROOT') }}"
    deployment_remote_path: /vulpes/ngi

  pre_tasks:
    - include: tasks/pre-install.yml
      tags: always

  environment:
    "{{ tools_path }}"

  roles:
    - { role: ngi_pipeline, tags: ngi_pipeline }
    - { role: func_accounts, tags: func_accounts }
    - { role: nextflow, tags: nextflow }
    - { role: tarzan, tags: tarzan }
    - { role: taca, tags: taca }
    - { role: ngi_reports, tags: ngi_reports }
    - { role: multiqc, tags: multiqc }
    - { role: arteria-staging, tags: arteria-staging }
    - { role: arteria-checksum-ws, tags: arteria-checksum }
    - { role: arteria-delivery-ws, tags: arteria-delivery }
    - { role: standalone_scripts, tags: standalone_scripts }
    - { role: ugc, tags: ugc }
    - { role: misc-tools, tags: misc-tools }
    - { role: archive-upload-ws, tags: archive-upload }
    - { role: nf-core, tags: nf-core }

  post_tasks:
    - include: tasks/post-install.yml
      tags: always
