---
taca_ngi_repo: https://github.com/NationalGenomicsInfrastructure/taca-ngi-pipeline.git
taca_ngi_dest: "{{ sw_path }}/taca-ngi-pipeline"
taca_ngi_version: c175edf1d4e8db887c8c54f06bf1947cc5b34345

flowcell_parser_repo: https://github.com/NationalGenomicsInfrastructure/flowcell_parser.git
flowcell_parser_dest: "{{ sw_path }}/flowcell_parser"
flowcell_parser_version: 286b54825a83ef5cfed5345752f56b7e93265a1a

taca_repo: https://github.com/NationalGenomicsInfrastructure/TACA.git
taca_dest: "{{ sw_path }}/TACA"
taca_version: cc2da6b8df55ef7419a3accebf7c9a33ab8e4d9e

ngi_pipeline_analysisdir: "{{ ngi_pipeline_workdir }}/ANALYSIS"
ngi_pipeline_datadir: "{{ ngi_pipeline_workdir }}/DATA"
ngi_pipeline_deliverydir: "{{ ngi_pipeline_workdir }}/DELIVERY"
