---

- name: ensure {{ arteria_service_name }} conf dir exists
  file:
    state: directory
    path: "{{ arteria_service_config_root }}"

- name: Download {{ arteria_service_name }} app config
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/Molmed/checkQC/refs/tags/{{ checkqc_version }}/checkQC/default_config/config.yaml"
    dest: "{{ arteria_service_config_root }}/app.config"
    mode: "0664"

- name: Update bcl2fastq output path
  ansible.builtin.lineinfile:
    path: "{{ arteria_service_config_root }}/app.config"
    regexp: '^bcl2fastq_output_path: Data/Intensities/BaseCalls$'
    line: 'bcl2fastq_output_path: Unaligned'

- name: Update reports_location:
  ansible.builtin.lineinfile:
    path: "{{ arteria_service_config_root }}/app.config"
    regexp: '^reports_location: Reports$'
    line: 'resports_location: Unaligned/Stats'

- name: deploy {{ arteria_service_name }} logger config
  template:
    src: checkqc_logger.config.j2
    dest: "{{ arteria_service_config_root }}/logger.config"

- name: modify uppsala's supervisord conf to start {{ arteria_service_name }}
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: program:{{ arteria_service_name }}-{{ deployment_environment }}
    option: command
    value: >
      {{ arteria_service_env_root }}/bin/checkqc-ws
      --config {{ arteria_service_config_root }}/app.config
      --log_config {{ arteria_service_config_root }}/logger.config
      --port={{ checkqc_service_port }}
      {{ static_runfolder_path }}
    backup: no

- name: modify uppsala's supervisord conf to start {{ arteria_service_name }}
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: "program:{{ arteria_service_name }}-{{ deployment_environment }}"
    option: autorestart
    value: true
    backup: no
