---
arteria_service_name: arteria-olink
arteria_olink_service_log: "{{ arteria_service_log_dir }}/{{ arteria_service_name }}.log"

olink_ngs2counts_dir: "/vulpes/ngi/containers/ngs2counts"
olink_ngs2counts_default: "6.2.2"

olink_ngs2counts_nf_workflow: "https://github.com/Molmed/ngs2counts_nextflow.git"
olink_ngs2counts_nf_workflow_version: "1.0.0"
